= Testing with JPMS (java platform module system, 'jigswaw')
:toc:

== introduction
The short version of this: it is hard.

When searching for this you inevitable end up on this URL:

https://sormuras.github.io/blog/2018-09-11-testing-in-the-modular-world.html

This is however more a proposal, and to actually use it you need to use a maven plugin provided by sormuras.

I considered it but:

- It seems overly complicated
- Support from IDE seems missing


== Intellij
Does not supported `module-info.java` shadowing. It doesn't recognize `module-info.test` at all.


== Maven
This is all about surefire/failsafe plugins. I think they do support module-info shadowing, but it it hard without proper support of IDE. Shadowing should enabled whitebox testing (by e.g. giving access to junit framework, to parts of the code that actually should be hidden)

== Blackbox vs whitebox testing
Blackbox testing should in principle be more straightforward. You could simply make a new maven module, and place your tests in a entire new jigsaw module.



All this is a bit annoying, because in every setup I could think of it would give rather a lot of boiler place.

- Place blackbox tests in a directory next to `main` and test `test`
- Place blackbox tests in a module below the current one
- Place blackbox tests in a module next to the current one


Blackbox testing is less flexible, and I generally considered testing a valid argument for 'white boxing', i.e. e.g. accessing package access methods.

