---
name: release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      # See https://stackoverflow.com/questions/70153962/nexus-staging-maven-plugin-maven-deploy-failed-an-api-incompatibility-was-enco
      MAVEN_ARGS: --no-transfer-progress
      MAVEN_OPTS:  --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED
    steps:
      - name: check branch name
        run: |
            if [[ ${{ github.ref }} =~ refs/heads/[0-9]+\.[0-9]+-SNAPSHOT ]]; then
              echo "valid_branch=true" >>  $GITHUB_ENV
            else
              echo "valid_branch=false" >>  $GITHUB_ENV
              echo "halting release process since this is not a release branch. ${{ github.ref }} must be refs/heads/[0-9]+\.[0-9]+-SNAPSHOT"
              exit 1
            fi
      - uses: actions/checkout@v5
        if: ${{ env.valid_branch  == 'true' }}
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      - name: Fix bom
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils
          .github/fix-bom.sh -B -R
      - name: Commit changes in bom if necessary
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: bom changes
      - name: Build BOM with Maven
        run: (cd i18n-regions-bom ; mvn -B -Pdeploy clean deploy) ; echo BOM was built
        continue-on-error: true  # sometimes it was released already in a previous fail
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
      - name: Release
        run: |
          git config --global user.name 'github actions'
          git config --global user.email 'github@meeuw.org'
          mvn --batch-mode  -Darguments=-DskipTests  -DpushChanges=false release:prepare
          git push --atomic -v --follow-tags
          mvn -P'deploy,!blackboxtesting' --batch-mode -Darguments=-DskipTests release:perform
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
